name: Compile CV
run-name: Compiling CVs according to options !
on:
  push:
    branches: [ master, feat/github-actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: kjarosh/latex:2024.4
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: clean up
        run: make clean
      
      - name: build pdfs
        run: make all

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CVs
          path: ./out
