name: Compile CV
run-name: Compiling all of the CVs according to options !
on:
  push:
    branches: [ master, feat/github-actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: kjarosh/latex:2024.4
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: compile CV without picture
        run: pdflatex --output-directory="out" -jobname=cv main.tex

      - name: set environment variable
        run: export WITHPIC="true"

      - name: compile CV with picture
        run: pdflatex --output-directory="out" -jobname=cv_pic main.tex

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CVs
          path: ./out
