name: Compile CV
run-name: Compiling all of the CVs according to options !
on:
  push:
    branches: [ main, feat/github-actions ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: blang/latex
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: compile CV
        run: pdflatex main.tex
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: cv.pdf
          path: ./main.pdf
